services:
  - type: web
    name: blake
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blake.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blake-db
