# Generated by Django 5.1.4 on 2025-01-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group', max_length=100)),
                ('emails', models.JSONField(help_text='List of email addresses in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject of the email', max_length=255)),
                ('body', models.TextField(help_text='Body of the email')),
                ('scheduled_time', models.DateTimeField(help_text='Time to send the emails')),
                ('smtp_account', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], help_text='SMTP account to use for sending emails', max_length=100)),
                ('sent', models.BooleanField(default=False, help_text='Whether the campaign has been sent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.emailgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Time when the email was sent', null=True)),
                ('replied', models.BooleanField(default=False, help_text='Whether the recipient replied to the email')),
                ('email_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.emailcampaign')),
            ],
        ),
    ]
