# Generated by Django 5.1.4 on 2025-01-17 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailgroup',
            name='emails',
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='email',
            field=models.EmailField(default=object, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
